version: '3'
services:
  consul:
    image: 'hashicorp/consul'
    ports:
      - '8500:8500'
  mysql:
    image: "mysql:9.1.0"
    ports:
      - 13306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
  redis:
    image: "redis:latest"
    ports:
      - 16379:6379
